### ISSUE TITLE
Depth evaluation went wrong

### ISSUE THREAD

**Issue by XiangMochu** [srrichter/viper#12]
I followed the instruction in the toolkit to process my depth prediction results, but after uploading, it says that my upload was not evaluated for something went wrong.

Specifically, I have used the `imageio`, `justpfm` library and the function from [MiDaS](https://github.com/isl-org/MiDaS/blob/master/utils.py#L59) to save my prediction to a pfm image (but none of them can give a successful evaluation), after converting their format into `np.float32`. Then I run `prepare_submission.py depth <path_to_my_predictions>` and got response as `Submission file is ... . Please upload it at ...`. After Uploading my submission `depth_submission.bin`, I got an error page telling me that my results are not evaluated. 

Are there any potential reasons that can cause this issue? Did I miss some necessary steps? Do I have to save pfm files following some specific steps?

**Comment by srrichter** [comment]
Submissions generated with the toolkit generally have the right format. We are currently experiencing some issues with the server, leading to "Something went wrong" error messages. If that happens to you, please contact us via the contact form and provide user name and method name. We'll check and run the evaluation manually if necessary.
