### ISSUE TITLE
Submission of Monocular depth estimation

### ISSUE THREAD

**Issue by wanderHZ** [srrichter/viper#9]
This file(encode_depth_submission ) only processes 2481 pfm files, but there are 2500 data in the test list. Is this our problem? Or is the test list of the depth estimation task 2481 data? Look forward to your reply, thank you!

**Comment by srrichter** [comment]
The binary encode_depth_submission samples a subset of the complete test set (containing 2500 frames) and compresses them for the submission. If the binary produces a submission file, you should be fine.
